version: '3.8'
services:
  
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: etot
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 33066:3306

  phpMyAdmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "9090:80"

  excel_to_table:
    image: shivamhkhr/excel-to-table:latest  # Updated image attribute
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./excel_to_table:/app
    ports:
      - "8001:8001"
    environment:
      - DJANGO_SETTINGS_MODULE=excel_to_table.settings
    depends_on:
      - db
