# Generated by Django 5.0.1 on 2024-01-11 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='template_master',
        ),
        migrations.AddField(
            model_name='userpermission',
            name='upload_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.uploadtemplate', verbose_name='template name'),
        ),
    ]
