# Generated by Django 4.2.6 on 2023-10-25 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('std_value', models.CharField(max_length=200)),
                ('obs_value', models.CharField(max_length=200)),
                ('end_time', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'tbl_templatemaster',
            },
        ),
        migrations.CreateModel(
            name='Usertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Type Name')),
                ('password', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'tbl_usertable',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.templatemaster', verbose_name='User Type')),
                ('user_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.usertable', verbose_name='User Type')),
            ],
        ),
    ]
