# Generated by Django 4.2.6 on 2023-10-26 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_processtable_templatemaster_usertable_userpermission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcessTable',
            new_name='TemplateDetail',
        ),
        migrations.AlterModelTable(
            name='templatedetail',
            table='tbl_templatedetail',
        ),
        migrations.AlterModelTable(
            name='userpermission',
            table='tbl_userpermission',
        ),
    ]
