# Generated by Django 5.0.1 on 2024-01-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_userpermission_template_master_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpermission',
            old_name='upload_template',
            new_name='template_master',
        ),
        migrations.AlterField(
            model_name='uploadtemplate',
            name='worksheet_name',
            field=models.CharField(default=True, max_length=150, unique=True),
        ),
    ]
