# Generated by Django 5.0.1 on 2024-01-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_upload_template_userpermission_template_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadtemplate',
            name='worksheet_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
