# Generated by Django 5.0.1 on 2024-01-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_uploadtemplate_worksheet_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemplateMaster',
        ),
        migrations.RenameField(
            model_name='userpermission',
            old_name='template_master',
            new_name='upload_template',
        ),
    ]
