# Generated by Django 5.0.1 on 2024-01-12 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_templatemaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='user_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.usertable', verbose_name='User name'),
        ),
    ]
