# Generated by Django 5.0.1 on 2024-01-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_userpermission_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatedetail',
            name='creator',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
