# Generated by Django 5.0.1 on 2024-01-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_templatedetail_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadtemplate',
            name='worksheet_name',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
