# Generated by Django 5.0.1 on 2024-01-18 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_uploadtemplate_worksheet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='user_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.usertable', verbose_name='User name'),
        ),
    ]
