# Generated by Django 5.0.1 on 2024-01-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_userpermission_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadtemplate',
            name='worksheet_file',
            field=models.FileField(default=True, null=True, upload_to='worksheets'),
        ),
    ]
