# Generated by Django 5.0.1 on 2024-01-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_uploadtemplate_worksheet_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadtemplate',
            name='worksheet_file',
            field=models.FileField(null=True, upload_to='worksheets'),
        ),
    ]
