# Generated by Django 5.0.1 on 2024-01-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_uploadtemplate_worksheet_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadtemplate',
            name='worksheet_file',
            field=models.FileField(default=True, upload_to='worksheets'),
        ),
    ]
