# Generated by Django 5.0.1 on 2024-01-22 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_uploadtemplate_worksheet_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatedetail',
            name='template_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='uploadtemplate',
            name='worksheet_file',
            field=models.FileField(default=True, upload_to='template'),
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=150, null=True, unique=True)),
                ('form_file', models.FileField(default=True, upload_to='form')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.usertable')),
            ],
            options={
                'db_table': 'tbl_form',
            },
        ),
        migrations.CreateModel(
            name='FormDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('std_value', models.CharField(max_length=200)),
                ('obs_value', models.CharField(max_length=200)),
                ('start_time', models.CharField(max_length=200)),
                ('end_time', models.CharField(max_length=200)),
                ('creator', models.CharField(max_length=200, null=True)),
                ('form_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.form', verbose_name='Form')),
                ('upload_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.uploadtemplate', verbose_name='Template')),
            ],
            options={
                'db_table': 'tbl_formdetail',
            },
        ),
        migrations.AddField(
            model_name='userpermission',
            name='form_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.formdetail', verbose_name='form name'),
        ),
    ]
