# Generated by Django 5.0.1 on 2024-01-22 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_templatedetail_template_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='creator',
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='form_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.formdetail', verbose_name='form name'),
        ),
    ]
