# Generated by Django 5.0.1 on 2024-01-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_form_creator_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='UploadedForm',
        ),
    ]
