# Generated by Django 5.0.1 on 2024-01-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_form_uploadedform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedform',
            name='form_file',
        ),
    ]
