# Generated by Django 5.0.1 on 2024-01-23 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_uploadedform_form_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='form_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.uploadedform', verbose_name='form name'),
        ),
    ]
