# Generated by Django 5.0.1 on 2024-01-24 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_userpermission_form_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatedetail',
            name='template_name',
        ),
        migrations.AddField(
            model_name='templatedetail',
            name='upload_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.uploadtemplate'),
        ),
    ]
