# Generated by Django 5.0.1 on 2024-01-24 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_templatedetail_template_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='form_details',
        ),
        migrations.CreateModel(
            name='TempFormRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.uploadedform', verbose_name='form name')),
                ('upload_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.uploadtemplate', verbose_name='template name')),
                ('user_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.usertable', verbose_name='User name')),
            ],
            options={
                'db_table': 'tbl_tempformrelation',
            },
        ),
    ]
